### ISSUE TITLE
str does not work

### ISSUE THREAD

**Issue by coryryan269** [Wunkolo/OakSim#5]
**str** instruction causes a crash.
		
            add             r1, r0, #0x12
		lsl		r1, r1, #8
		add		r1, r1, #0x34
		
		add		r2, r2, #0x01
		lsl		r2, r2, #16
		add		r2, r2, #0xc0
		
		
		str		r2, [r1]

This leads to the following message:
abort() at jsStackTrace@file:///home/cory/Desktop/OakSim-master/lib/unicorn-arm.min.js:5:18821 stackTrace@file:///home/cory/Desktop/OakSim-master/lib/unicorn-arm.min.js:5:18992 abort@file:///home/cory/Desktop/OakSim-master/lib/unicorn-arm.min.js:29:7211 _abort@file:///home/cory/Desktop/OakSim-master/lib/unicorn-arm.min.js:5:200315 YB@file:///home/cory/Desktop/OakSim-master/lib/unicorn-arm.min.js:13:134507 Sz@file:///home/cory/Desktop/OakSim-master/lib/unicorn-arm.min.js:17:127559 GRa@file:///home/cory/Desktop/OakSim-master/lib/unicorn-arm.min.js:9:184719 invoke_iiiiii@file:///home/cory/Desktop/OakSim-master/lib/unicorn-arm.min.js:5:284951 WC@file:///home/cory/Desktop/OakSim-master/lib/unicorn-arm.min.js:19:111734 SC@file:///home/cory/Desktop/OakSim-master/lib/unicorn-arm.min.js:19:99989 RC@file:///home/cory/Desktop/OakSim-master/lib/unicorn-arm.min.js:19:99479 RH@file:///home/cory/Desktop/OakSim-master/lib/unicorn-arm.min.js:11:132730 ccallFunc@file:///home/cory/Desktop/OakSim-master/lib/unicorn-arm.min.js:5:9906 Unicorn/this.emu_start@file:///home/cory/Desktop/OakSim-master/lib/unicorn-arm.min.js:313:32 CurContext

**Comment by Wunkolo** [comment]
This looks to be an error up-stream as my front-end just feeds into the [unicorn](https://github.com/AlexAltea/unicorn.js)/[kapstone](https://github.com/AlexAltea/keystone.js) backend. The callstack implies this is an issue with `unicorn` in particular.
This is also a very very old school project that I am no longer supporting unfortunately.
